// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "baseUrl": string;
      "apiKey": string;
      "model": string;
      "temperature": string;
      "maxContextTokens": number;
      "defaultMode": string;
      "autoSummarizeOnOpen": boolean;
      "systemPrompt": string;
      "summarySystemPrompt": string;
      "charsPerToken": string;
    };
  }
}
